# Generated by Django 3.2.8 on 2021-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='options',
            field=models.CharField(choices=[('DFT', 'Draft'), ('SBT', 'Submitted'), ('PB', 'Published'), ('RJT', 'Rejected')], default='DFT', max_length=3),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
