# Generated by Django 3.2.8 on 2021-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catergories',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
