# Generated by Django 3.2.8 on 2021-10-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_catergories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='catergories',
            new_name='categories',
        ),
    ]
